package com.models.notifications;

public enum NotificationType {
	ACCEPTED_FRIEND_REQUEST,
	FRIEND_REQUEST,
	AREA_ENTERED,
	AREA_LEFT,
	EVENT_INVITATION,
	EVENT_ARRIVAL,
	EVENT_DELETION,
	EVENT_EDITING
}
